rm -rf ../../../cocos2d/cocos/platform/android/java/bin/*
rm -rf ../../../cocos2d/cocos/platform/android/java/gen/*
rm -rf ../../common/LibHNMarket/platform/android/HNMarket/bin/*
rm -rf ../../common/LibHNMarket/platform/android/HNMarket/gen/*
rm -rf ../../common/LibHNMarket/platform/android/HNPay/bin/*
rm -rf ../../common/LibHNMarket/platform/android/HNPay/gen/*
rm -rf ../../common/libs/*
rm -rf proj.android/bin/*
rm -rf proj.android/gen/*
rm -rf proj.android/obj/*
